# Generated by Django 6.0.2 on 2026-02-27 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Mare', 'Mare'), ('Stallion', 'Stallion'), ('Gelding', 'Gelding')], max_length=20)),
                ('year_of_birth', models.IntegerField(blank=True, null=True)),
                ('height_cm', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('studbook', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pony_images/')),
                ('breeder', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('fei_id', models.CharField(blank=True, max_length=50)),
                ('ueln', models.CharField(blank=True, max_length=50)),
                ('microchip', models.CharField(blank=True, max_length=50, null=True)),
                ('is_approved_stallion', models.BooleanField(default=False)),
                ('is_at_stud', models.BooleanField(default=False)),
                ('approval', models.CharField(blank=True, max_length=255)),
                ('semen_type', models.CharField(blank=True, max_length=255)),
                ('breeding_fee', models.CharField(blank=True, max_length=255)),
                ('breeding_location', models.CharField(blank=True, max_length=255)),
                ('breeding_contact', models.CharField(blank=True, max_length=255)),
                ('wffs_status', models.CharField(blank=True, choices=[('Negative', 'Negative'), ('Positive', 'Positive'), ('Carrier', 'Carrier'), ('Unknown', 'Unknown')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_offspring', to='ponies.pony')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sire_offspring', to='ponies.pony')),
            ],
        ),
        migrations.CreateModel(
            name='PonyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pony_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('pony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ponies.pony')),
            ],
        ),
    ]
