# Generated by Django 6.0.2 on 2026-03-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pony',
            name='competition_record',
            field=models.TextField(blank=True),
        ),
    ]
