# Generated by Django 6.0.2 on 2026-03-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponies', '0002_pony_competition_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='pony',
            name='stallion_holder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
