# Generated by Django 6.0.2 on 2026-03-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponies', '0003_pony_stallion_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pony',
            name='breeding_contact',
        ),
        migrations.RemoveField(
            model_name='pony',
            name='breeding_location',
        ),
        migrations.RemoveField(
            model_name='pony',
            name='semen_type',
        ),
        migrations.AddField(
            model_name='pony',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pony',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pony',
            name='owner_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
