# Generated by Django 6.0.2 on 2026-03-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponies', '0004_remove_pony_breeding_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pony',
            old_name='owner_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='pony',
            old_name='owner_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='pony',
            old_name='breeding_fee',
            new_name='stud_fee',
        ),
        migrations.RenameField(
            model_name='pony',
            old_name='owner_website',
            new_name='website',
        ),
    ]
