# Generated by Django 6.0.2 on 2026-03-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponies', '0005_rename_owner_email_pony_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pony',
            old_name='approval',
            new_name='approved_for',
        ),
    ]
