# Generated by Django 6.0.2 on 2026-03-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponies', '0006_rename_approval_pony_approved_for'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.AddField(
            model_name='pony',
            name='dam_name_fallback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pony',
            name='sire_name_fallback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
