# Generated by Django 6.0.2 on 2026-03-19 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponies', '0007_delete_contactmessage_pony_dam_name_fallback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('show', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('competition', models.CharField(max_length=255)),
                ('observed_height', models.CharField(blank=True, max_length=50, null=True)),
                ('athlete', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=50)),
                ('score', models.CharField(max_length=50)),
                ('pony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponies.pony')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
