# Generated by Django 6.0.2 on 2026-03-19 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponies', '0008_competitionresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitionresult',
            old_name='observed_height',
            new_name='obs_height',
        ),
    ]
