# Generated by Django 6.0.2 on 2026-03-20 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponies', '0009_rename_observed_height_competitionresult_obs_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionresult',
            name='pony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_records', to='ponies.pony'),
        ),
    ]
