# Generated by Django 6.0.2 on 2026-03-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponies', '0010_alter_competitionresult_pony'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/competition/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
