# Generated by Django 6.0.2 on 2026-03-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponies', '0011_competitionupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='pony',
            name='pedigree_image',
            field=models.ImageField(blank=True, null=True, upload_to='pedigrees/'),
        ),
    ]
