# Generated by Django 6.0.2 on 2026-03-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponies', '0012_pony_pedigree_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pony',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ponies/images/'),
        ),
        migrations.AlterField(
            model_name='pony',
            name='pedigree_image',
            field=models.ImageField(blank=True, help_text='Upload the pedigree image here', null=True, upload_to='ponies/pedigree_images/'),
        ),
    ]
